name: C/C++ CI

on:
  push:
    branches: [ "demo-with-RTOS" ]
  pull_request:
    branches: [ "demo-with-RTOS" ]
  workflow_dispatch:  # Manually trigger this workflow

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: move-to-dir
      run: |
          cd DemoMakeFile
          ls
    - name: make-clean
      run: |
           ls
           cd DemoMakeFile
           ls
           make -j16 -f STM32Make.make clean      
    - name: make 
      run: make -j16 -f STM32Make.make
