name: C/C++ CI

on:
  push:
    branches: [ "demo-with-RTOS" ]
  pull_request:
    branches: [ "demo-with-RTOS" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: ./configure
    - name: make clean
      run: make DemoMakeFile/STM32Make.make clean
    - name: make 
      run: make DemoMakeFile/STM32Make.make
